name: online-theatre-user-profiles-lint

services:
  auth:
    build:
      context: ./compose/auth
      target: lint
    networks:
      - movies-network
    volumes:
      - 'auth-mypy-cache:/opt/app/.mypy_cache'
      - './compose/auth/.lint:/opt/app/.lint'
    command: [ 'sleep', 'infinity' ]
    develop:
      watch:
        - action: sync
          path: ./compose/auth/auth
          target: /opt/app/auth
        - action: sync
          path: ./compose/auth/scripts
          target: /opt/app/scripts
        - action: rebuild
          path: ./compose/auth/commands
        - action: rebuild
          path: ./compose/auth/pyproject.toml
        - action: rebuild
          path: ./compose/auth/poetry.lock

networks:
  movies-network:

volumes:
  auth-mypy-cache:
